---
abstract: 'more sugar for MooseX::Declare'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::DeclareX
name: MooseX-DeclareX
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Load: 0
  Data::OptList: 0
  Devel::Declare: 0
  Devel::Declare::Context::Simple: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util: 0
  MooseX::ABCD: 0
  MooseX::Declare: 0
  MooseX::Declare::Context::WithOptions::Patch::Extensible: 0
  MooseX::Method::Signatures: 0
  MooseX::Privacy: 0
  Sub::Install: 0
  TryCatch: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-DeclareX
  homepage: https://metacpan.org/release/MooseX-DeclareX
  license: http://dev.perl.org/licenses/
version: 0.001
